---
layout: post
title: 예외처리
categories: JAVA
tags: [JAVA]
---
프로그램을 실행할 때 발생하는 오류를 무시하거나 그에 맞는 적절한 처리를 할 때 쓰인다

보통 컴파일 시 발생하는 예외의 경우 IDE 사용 시 예외를 처리하라고 표시한다

하지만 컴파일 시 발견하지 못하는 예외의 경우 런타임 에러라고 하는데 이때는 프로그래머가 직접 예측하여 처리해야 한다

그리고 그런 예외가 발생했을때 어떤 동작을 처리해야하는지를 예외 처리라고 한다.

오류 예시(어떤 수를 0으로 나눌 경우)
<pre>
<code>
public class ErrorTest {
    public static void main(String[] args) {
        int a,b;
        a=10;
        b=0;

        int c=a/b;
        System.out.println(c);
    }
}
</code>
</pre>
출력 :
<pre>
<code>
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at test.ErrorTest.main(ErrorTest.java:9)
</code>
</pre>

## try, catch
예외가 발생했을 때 이를 처리하거나 메소드를 호출한 곳으로 던진다

*모든 예외는 Exception이라는 클래스를 상속받는다

예시 :
<pre>
<code>
public static void main(String[] ar){
	int a,b;
	a=10;
	b=0;
	try {
		int c=a/b;
		System.out.println(c);	//예외발생으로 실행 불가한 코드
	}catch(ArithmeticException e) { //ArithmeticException이 발생했다면
		System.out.println("ArithmeticException 발생");
		System.out.println("0으로 나눌 수는 없습니다");
		e.printStackTrace(); //어느 부분에서 예외가 발생했는지 알려주는 추적로그
	}finally { //어떤 예외가 발생하던 말던 무조건 실행
		System.out.println("finally 실행");
	}
}
</code>
</pre>
출력 :
<pre>
<code>
ArithmeticException 발생
0으로 나눌 수는 없습니다
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at test.ErrorTest.main(ErrorTest.java:9)
finally 실행
</code>
</pre>
## throws
메소드를 호출한 곳으로 예외 처리를 떠넘기는 것

예시 :
<pre>
<code>
public class ErrorTest {
    public static void divide(int a,int b) throws ArithmeticException {
        if(b==0) throw new ArithmeticException("안 돼"); //devide()를 호출한 main에서 처리
        int c=a/b;
        System.out.println(c);
    }
    public static void main(String[] ar){
        int a=10;
        int b=0;

        try {
            divide(a,b);
        }catch(ArithmeticException e) {
            e.getMessage(); //Exception 생성자 중에서 메시지를 받는 생성자가 있는데, 메시지를 볼 때 이용
            e.printStackTrace();
        }
    }
}
</code>
</pre>
출력 :
<pre>
<code>
java.lang.ArithmeticException: 안 돼
	at test.ErrorTest.divide(ErrorTest.java:5)
	at test.ErrorTest.main(ErrorTest.java:14)
</code>
</pre>